//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _21._102_02_PreFinalExam.dbModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registration
    {
        public int ID { get; set; }
        public int ClientID { get; set; }
        public int ServiceID { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Services Services { get; set; }
    }
}
